### ISSUE TITLE
have any managed to get groceries + traefik to work?

### ISSUE THREAD

**Issue by KongGal** [davideshay/groceries#126]
Have any managed to get the 2 to work together?  
Couchdb i got working  and can acceses it  
got labels setup for it as well  

    labels:  
      - "traefik.enable=true"  
      - "traefik.http.routers.listdb-http.rule=Host(`listdb.tld.me`)"  
      - "traefik.http.routers.listdb-http.entrypoints=web"  
      - "traefik.http.routers.listdb-http.middlewares=redirect-websecure"  
      - "traefik.http.middlewares.redirect-websecure.redirectscheme.scheme=https"  
      - "traefik.http.routers.listdb.rule=Host(`listdb.tld.me`)"  
      - "traefik.http.routers.listdb.entrypoints=websecure"  
      - "traefik.http.routers.listdb.tls.certresolver=cloudflare"  
      - "traefik.http.services.listdb.loadbalancer.server.port=5984"  
      - "traefik.http.routers.listdb.middlewares=listdb"  
      - "traefik.http.middlewares.listdb.headers.customFrameOptionsValue=SAMEORIGIN"  
      - "traefik.http.middlewares.listdb.headers.contentSecurityPolicy=frame-ancestors 'self' listdb.tld.me"  
      - "traefik.http.middlewares.listdb.headers.stsSeconds=155520011"  
      - "traefik.http.middlewares.listdb.headers.stsPreload=true"  
      - "traefik.http.middlewares.listdb.headers.contentTypeNosniff=true"  
      - "traefik.http.middlewares.listdb.headers.browserXSSFilter=true"  
    
The frontend is running and somewhat working    
it starts up, When i load the i get a few `Detected cannot start, setting initRemoteState` i can load the page but i do get some CSP issues as well that worker-srv blob is being blocked by Content Security Policy  
when i try and make an account i get some issues about worker-srv and also error 405 with Method Not Allowed when regstering and when trying to login, for the worker-srv i tried adding worker-src 'self' blob: 'list.tld.me' to the CSP string but no luck.. as it getting blocked.  
  
if i then try and create a user account i just get `POST https://list.tld.me/registernewuser 405 (Method Not Allowed)`  
the labels i use for frontend is the following.  
  
    labels:  
      - "traefik.enable=true"  
      - "traefik.http.routers.list-http.rule=Host(`list.tld.me`)"  
      - "traefik.http.routers.list-http.entrypoints=web"  
      - "traefik.http.routers.list-http.middlewares=redirect-websecure"  
      - "traefik.http.middlewares.redirect-websecure.redirectscheme.scheme=https"  
      - "traefik.http.routers.list.rule=Host(`list.tld.me`)"  
      - "traefik.http.routers.list.entrypoints=websecure"  
      - "traefik.http.routers.list.tls.certresolver=cloudflare"  
      - "traefik.http.services.list.loadbalancer.server.port=8100"  
      - "traefik.http.routers.list.middlewares=list"  
      - "traefik.http.middlewares.list.headers.customFrameOptionsValue=SAMEORIGIN"  
      - "traefik.http.middlewares.listdb.headers.contentSecurityPolicy=frame-ancestors 'self' listdb.tld.me; worker-src blob:"  
      - "traefik.http.middlewares.list.headers.stsSeconds=155520011"  
      - "traefik.http.middlewares.list.headers.stsPreload=true"  
      - "traefik.http.middlewares.list.headers.contentTypeNosniff=true"  
      - "traefik.http.middlewares.list.headers.browserXSSFilter=true"  
 
    
if i have a look in the logs i see this for couchdb  
`open_result error {not_found,no_db_file} for _replicator  
`    
    
for backend i get this  
Not sure yet if i need labels somehow to route /api traffic to 3333  

```
backend-groceries-server   | (node:8) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.  
backend-groceries-server   | (Use `node --trace-deprecation ...` to show where the warning was created)  
backend-groceries-server   | [04:31:24] INFO: Starting up auth server for couchdb...  
backend-groceries-server   | [04:31:24] INFO: App Version:  1.1.4  
backend-groceries-server   | [04:31:24] INFO: Database Schema Version: 6  
backend-groceries-server   | [04:31:24] INFO: Database URL:  https://listdb.tld.me:5984  
backend-groceries-server   | [04:31:24] INFO: Internal Database URL:  https://list-db:5984  
backend-groceries-server   | [04:31:24] INFO: Using database: groceries  
backend-groceries-server   | [04:31:24] INFO: Refresh token expires in  30d(2592000 seconds)  
backend-groceries-server   | [04:31:24] INFO: STATUS: Access token expires in  12h(43200 seconds)  
backend-groceries-server   | [04:31:24] INFO: STATUS: User Account Creation is:  ENABLED  
```

**Comment by jrbarronumd** [comment]
I do have this working with Traefik, set up more than a year ago, so my memory on the process is a bit shaky, but there were some challenges.  That said, I don't remember the specific errors you're seeing.

I have the routers set up in a dynamic config file and middlewares in another dynamic file, so may need a bit of translating.

Full router config (the 'chain-no-auth' is just my standard security/headers/compression, but the other middlewares were necessary to get the app working for me):
```
http:
  routers:
    groceries-rtr:
      rule: "Host(`groceries.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - https
      middlewares:
        - middlewares-groceries-cors
        - chain-no-auth
      service: groceries-svc
      tls:
        certResolver: dns-cloudflare
    groceries-api-rtr:
      rule: "Host(`groceries.{{env "DOMAINNAME"}}`) && PathPrefix(`/api`)"
      entryPoints:
        - https
      middlewares:
        - middlewares-groceries-cors
        - chain-no-auth
        - middlewares-groceries-api
      service: groceries-api-svc
      tls:
        certResolver: dns-cloudflare
  services:
    couchdb-svc:
      loadBalancer:
        servers:
          - url: "http://groceries_db:5984"
    groceries-svc:
      loadBalancer:
        servers:
          - url: "http://groceries:80"
```

And the middleswares themselves, I think they came from the CouchDB docs, but I don't recall specifically:
```
http:
  middlewares:
    middlewares-groceries-cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowMethods:
          - OPTION
          - GET
          - POST
          - PUT
          - PATCH
        accessControlAllowHeaders:
          - Origin
          - Authorization
          - Content-Type
        accessControlAllowOriginList:
          - https://groceries.my.domain
          - https://couchdb.my.domain
        accessControlMaxAge: 100
        addVaryHeader: true
    middlewares-groceries-api:
      stripPrefix:
        prefixes:
          - "/api"
```
Not sure if this would address your particular errors, but I can tell you it is possible to get it working with Traefik, and I haven't had a single issue since getting it up and running.  I have since upgraded to Traefik 3.  I don't recall if I had to change this at all from 2 to 3, but at most I may have tweaked one thing due to deprecated syntax.

**Comment by KongGal** [comment]
Alright, gonna see if i can figure out how the heck to get that working with my setup that a mate setup for me >.<.. i already rage quit on this 5 times so far over the past 2 days :D

**Comment by kladderadeng** [comment]
I have it running with Traefik too. If you still have issues, I can look over my config, but since jrbarronumd already posted his which seems to work I hope you figured it out.

**Comment by KongGal** [comment]
> I have it running with Traefik too. If you still have issues, I can look over my config, but since jrbarronumd already posted his which seems to work I hope you figured it out.

Ended up giving up no matter what I did I just couldn't get it to expose the API at all spent so many hours and nothing I did worked

**Comment by kladderadeng** [comment]
I think stripping the prefixes was the key for me. As far as I can tell I have everything in my Compose file. I removed the secrets and will paste the whole Compose here, just if you want to try again some time and want a reference.

```
services:
  groceries-couchdb:
    container_name: groceries-couchdb
    hostname: groceries-couchdb
    image: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    healthcheck:
      test: curl --fail http://localhost:5984 || exit 1
      interval: 30s
      retries: 5
      start_period: 15s
      timeout: 10s
    environment:
      - COUCHDB_USER="admin"
      - COUCHDB_PASSWORD="thisisnotmypassword"
    volumes:
      - /opt/groceries/couchdb/dbdata:/opt/couchdb/data
      - /opt/groceries/couchdb/dbetclocal:/opt/couchdb/etc/local.d
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.publish=public"
      - "traefik.http.routers.groceries-couchdb.entrypoints=https"
      - "traefik.http.routers.groceries-couchdb.rule=Host(`groceries.my.domain`) && PathPrefix(`/db`)"
      - "traefik.http.routers.groceries-couchdb.tls=true"
      - "traefik.http.routers.groceries-couchdb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.groceries-couchdb.middlewares=default@file,groceries-couchdb-stripprefix"
      - "traefik.http.middlewares.groceries-couchdb-stripprefix.stripprefix.prefixes=/db"
      - "traefik.http.routers.groceries-couchdb.service=groceries-couchdb"
      - "traefik.http.services.groceries-couchdb.loadbalancer.server.port=5984"
      - "traefik.docker.network=vlanX"
    networks:
      vlanX:

  groceries-frontend:
    container_name: groceries-frontend
    hostname: groceries-frontend
    image: ghcr.io/davideshay/groceries-client:latest
    restart: unless-stopped
    depends_on:
      - groceries-backend
    environment:
      DEFAULT_API_URL: https://groceries.my.domain/api
      LOG_LEVEL: "D"
    ports:
      - "8100:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.publish=lan"
      - "traefik.http.routers.groceries-frontend.entrypoints=https"
      - "traefik.http.routers.groceries-frontend.rule=Host(`groceries-frontend.my.domain`)"
      - "traefik.http.routers.groceries-frontend.tls=true"
      - "traefik.http.routers.groceries-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.groceries-frontend.middlewares=default@file"
      - "traefik.http.routers.groceries-frontend.service=groceries-frontend"
      - "traefik.http.services.groceries-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=lan"
    volumes:
    - type: bind
      source: /opt/groceries/groceries-web-conf
      target: /etc/nginx/conf.d/default.conf
    networks:
      lan:

  groceries-backend:
    container_name: groceries-backend
    hostname: groceries-backend
    image: ghcr.io/davideshay/groceries-server:latest
    restart: unless-stopped
    depends_on:
      groceries-couchdb:
        condition: service_healthy
    environment:
      COUCHDB_URL: https://groceries.my.domain/db
      COUCHDB_INTERNAL_URL:  http://groceries-couchdb:5984
      COUCHDB_DATABASE: "groceries"
      COUCHDB_HMAC_KEY: "notmyhmackey"
      COUCHDB_ADMIN_USER: "admin"
      COUCHDB_ADMIN_PASSWORD: "notmypassword"
      GROCERY_URL: "https://groceries.my.domain"
      GROCERY_API_URL: "https://groceries.my.domain/api"
      GROCERY_API_PORT: "8000"
      SMTP_HOST: "mail.mail.server"
      SMTP_FROM: "groceries@my.domain"
      SMTP_PORT: "587"
      SMTP_USER: "grocries@my.comain"
      SMTP_PASSWORD:  "notmypassword"
      ENABLE_SCHEDULING: "true"
      RESOLVE_CONFLICTS_FREQUENCY_MINUTES: "3"
      EXPIRE_JWT_FREQUENCY_MINUTES: "60"
      ACCESS_TOKEN_EXPIRES: "12h"
      REFRESH_TOKEN_EXPIRES: "30d"
      LOG_LEVEL: "DEBUG"
      DISABLE_ACCOUNT_CREATION: "true"
    ports:
      - "8000:8000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.publish=public"
      - "traefik.http.routers.groceries-backend.entrypoints=https"
      - "traefik.http.routers.groceries-backend.rule=Host(`groceries.my.domain`) && PathPrefix(`/api`)"
      - "traefik.http.routers.groceries-backend.tls=true"
      - "traefik.http.routers.groceries-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.groceries-backend.middlewares=default@file,groceries-backend-stripprefix"
      - "traefik.http.middlewares.groceries-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.groceries-backend.service=groceries-backend"
      - "traefik.http.services.groceries-backend.loadbalancer.server.port=8000"
      - "traefik.docker.network=vlanX"
    networks:
      vlanX:

networks:
  vlanX:
    name: vlanX
    external: true
  lan:
    name: lan
    external: true
```

My middleware default@file is in the dynamic.yml of traefik and contains:

```
default:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
#       Deprecated
#       sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```


I do NOT expose the Web Interface to the Internet, this is why this is run via a 2nd Traefik Instance for my LAN instead of my VLAN that has the services that I expose to the Internet.

I hope this helps. It is really the best shopping list we (my family) ever had. I think it is worth it to try again, unless you found something else you are 100% happy with of course :-)
