### ISSUE TITLE
Web frontend does not load env-config.js

### ISSUE THREAD

**Issue by fuzzykiller** [davideshay/groceries#143]
I’m currently trying to install the application and find that the web frontend does not load `env-config.js`. As such, the API server URL is not prefilled correctly. The line `<script type="module" src="env-config.js"></script>` is probably removed during the build process.

**Comment by davideshay** [comment]
Not sure where you are trying to deploy it? If you are deploying the docker container, you should just set environment variables. Those then get placed into env-config.js by some startup scripts in the container.
In development mode, the same script runs to copy from .env into env-config.js.

**Comment by fuzzykiller** [comment]
I was attempting a Docker deployment, see full config (except CouchDB and Nginx) below. The file `env-config.js` is generated with the expected and correct contents. However, the frontend does not use it. Because, as described above, it simply never loads the file. It does not _fail_ to load the file, it does not _attempt to_ load the file.

Or at least, it did. I'm currently traveling and cannot verify the behavior persists.

---

```yml
services:
  couchdb:
    image: couchdb
    restart: always

    healthcheck:
      test: curl --fail http://localhost:5984 || exit 1
      interval: 30s
      retries: 5
      start_period: 15s
      timeout: 10s

    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb_config:/opt/couchdb/etc/local.d

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.groceries-db.loadbalancer.server.port=5984"
      - "traefik.http.routers.groceries-db.rule=Host(`db.groceries.example.com`)"
      - "traefik.http.routers.groceries-db.entryPoints=https,https6"
      - "traefik.http.routers.groceries-db.tls.certResolver=default"
      - "traefik.http.routers.groceries-db.middlewares=https-sts@file"


  frontend:
    image: ghcr.io/davideshay/groceries-client:latest
    restart: always

    environment:
      DEFAULT_API_URL: https://api.groceries.example.com/

    volumes:
      - ./groceries-web.conf:/etc/nginx/conf.d/default.conf

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.groceries-web.rule=Host(`groceries.example.com`)"
      - "traefik.http.routers.groceries-web.entryPoints=https,https6"
      - "traefik.http.routers.groceries-web.tls.certResolver=default"
      - "traefik.http.routers.groceries-web.middlewares=https-sts@file"


  backend:
    image: ghcr.io/davideshay/groceries-server:latest
    restart: always

    depends_on:
      - couchdb
    environment:
      COUCHDB_URL: https://db.groceries.example.com/
      COUCHDB_INTERNAL_URL:  http://couchdb:5984
      COUCHDB_DATABASE: groceries
      COUCHDB_HMAC_KEY: the-hmac-key
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASSWORD: the-admin-password
      GROCERY_URL: https://groceries.example.com
      GROCERY_API_URL: https://api.groceries.example.com
      GROCERY_API_PORT: 80
#   CHANGEME:  Change the SMTP variables to values that work for you to send outbound mail, if desired.
      SMTP_HOST: mx.example.com
      SMTP_FROM: admin@mytld.com
      SMTP_PORT: 587
      SMTP_USER: apikey
      SMTP_PASSWORD:  my-sendgrid-apikey
      ENABLE_SCHEDULING: 1
      RESOLVE_CONFLICTS_FREQUENCY_MINUTES: 3
      EXPIRE_JWT_FREQUENCY_MINUTES: 60
      ACCESS_TOKEN_EXPIRES: 12h
      REFRESH_TOKEN_EXPIRES: 30d
      DISABLE_ACCOUNT_CREATION: 1

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.groceries-api.rule=Host(`api.groceries.example.com`)"
      - "traefik.http.routers.groceries-api.entryPoints=https,https6"
      - "traefik.http.routers.groceries-api.tls.certResolver=default"
      - "traefik.http.routers.groceries-api.middlewares=https-sts@file"

networks:
  default:
    name: groceries

volumes:
  couchdb_data:
```
