### ISSUE TITLE
Docker backend has issues connecting with couchdb

### ISSUE THREAD

**Issue by MariusSp** [davideshay/groceries#18]
I tried to setup the docker setup via the provided compose file and the instructions. However after the couchdb initialization, the backend container exits shortly after docker-compose up. It seems like it is not able to communicate with the db:

```
groceries-server  | ERROR: could not retrieve database info.
groceries-server  | ERROR setting security: AxiosError: connect ECONNREFUSED 192.168.48.3:5984
groceries-server  |     at AxiosError.from (/usr/app/node_modules/axios/dist/node/axios.cjs:785:14)
groceries-server  |     at RedirectableRequest.handleRequestError (/usr/app/node_modules/axios/dist/node/axios.cjs:2733:25)
groceries-server  |     at RedirectableRequest.emit (node:events:511:28)
groceries-server  |     at eventHandlers.<computed> (/usr/app/node_modules/follow-redirects/index.js:14:24)
groceries-server  |     at ClientRequest.emit (node:events:511:28)
groceries-server  |     at Socket.socketErrorListener (node:_http_client:495:9)
groceries-server  |     at Socket.emit (node:events:511:28)
groceries-server  |     at emitErrorNT (node:internal/streams/destroy:151:8)
groceries-server  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
groceries-server  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
groceries-server  |   port: 5984,
groceries-server  |   address: '192.168.48.3',
groceries-server  |   syscall: 'connect',
groceries-server  |   code: 'ECONNREFUSED',
groceries-server  |   errno: -111,

```

Here is an excerpt from my compose file
```
  couchdb:
    container_name: couchdb
    image: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"

  groceries-server:
    depends_on:
      - couchdb
    container_name: groceries-server
    environment:
      COUCHDB_URL: http://localhost:5984
      COUCHDB_INTERNAL_URL:  http://couchdb:5984
      COUCHDB_DATABASE: "todos"
      GROCERY_URL: "http://localhost:8100"
      GROCERY_API_URL: "http://localhost:3333"
      GROCERY_API_PORT: "3333"
      ENABLE_SCHEDULING: "true"
      RESOLVE_CONFLICTS_FREQUENCY_MINUTES: "3"
      EXPIRE_JWT_FREQUENCY_MINUTES: "60"  
      ACCESS_TOKEN_EXPIRES: "12h"
      REFRESH_TOKEN_EXPIRES: "30d"      
    image: ghcr.io/davideshay/groceries-server:latest
    ports:
      - "3333:3333"
```
